### PR TITLE
eventyay platform added

### PR DESCRIPTION
**Pull request by mariobehling**
I have another open source platform for events for you that projects can use for monetization. Hope you like it.

### CODE REVIEW

**Review by bibryam — APPROVED** [review]

**Comment by bibryam** [comment]
Thanks Mario!

**Comment by bibryam** [comment]
Are there any stats you can share for the "activity: 20,000" field?
Number of events, or participants, or funds generated for the open source project?

**Comment by mariobehling** [comment]
The 20.000 field refers to the number of registered users, which is actually slightly higher by now.

**Comment by bibryam** [comment]
Thanks, I'll update the description. I've also done slight changes to categories and tags. 
Nice platform, thanks for adding it here. I'll schedule a tweet too.

Cheers,

**Pull request merged**
